# Generated by Django 2.1 on 2018-08-27 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import minesweeper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=datetime.datetime.now)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=minesweeper.models.TileStatus((0,)))),
                ('is_mine', models.BooleanField()),
                ('mines_around', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minesweeper.Game')),
            ],
        ),
    ]
