# Generated by Django 2.1 on 2018-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_difficulty_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-time_started']},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ['row', 'column']},
        ),
    ]
