# Generated by Django 2.1 on 2018-08-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0004_auto_20180828_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='minesweeper.Difficulty'),
        ),
    ]
