# Generated by Django 2.1 on 2018-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0005_auto_20180828_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Opened', 'Opened'), ('Flagged', 'Flagged')], default='Closed', max_length=7),
        ),
    ]
