# Generated by Django 2.1 on 2018-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0007_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opened_tiles',
            field=models.IntegerField(default=0),
        ),
    ]
