# Generated by Django 2.1 on 2018-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0009_tile_is_exploded_mine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='wrongly_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
