# Generated by Django 2.1 on 2018-08-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0011_auto_20180830_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='minesweeper.Difficulty'),
            preserve_default=False,
        ),
    ]
