# Generated by Django 2.1 on 2018-08-30 01:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0012_auto_20180830_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='columns',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='num_mines',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='rows',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_started',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
