# Generated by Django 2.1 on 2018-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0013_auto_20180830_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='is_mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tile',
            name='neighbouring_mines',
            field=models.IntegerField(default=0),
        ),
    ]
